Parameters:
    UbuntuAmiId:
      Description: Latest Ubuntu 18 AMI ID from parameter store
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    InstanceType:
      Description: EC2 Instance type
      Type: String
    myHomePublicIP:
      Description: My home public IP address
      Type: String

Resources:
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0  
  myEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref UbuntuAmiId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - Ref: mySecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/sdm"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: 10
      KeyName: project3
      Tags:
        - Key: Project
          Value: Udacity