version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@3.1
jobs:
  create-infrastructure:
    # executor: aws-cli/default
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - aws-cli/setup
      - run: |
          yum install -y tar gzip
          aws cloudformation create-stack \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --template-body file://ec2.yml \
            --parameters file://param.json \
            --region $AWS_DEFAULT_REGION
          echo "[all]" > ~/inventory
          sleep 100
          aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=Udacity" --output text >> ~/inventory
          cat ~/inventory
      - persist_to_workspace:
          root: ~/  
          paths: 
            - inventory
  # print-public-ip:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run: |
  #         yum install -y tar gzip
  #         cat ~/inventory
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
            fingerprints: ["ca:0e:3c:d2:b0:fe:9f:c9:28:50:75:17:20:b3:3f:a3"]
      - run: 
          name: Install Ansible
          command: |
            apk add --update ansible
            cat ~/inventory
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml
workflows:
  my_workflow:
    jobs:
      - create-infrastructure
      # - print-public-ip:
      #     requires: 
      #       - create-infrastructure  
      - configure-infrastructure:
          requires: 
            - create-infrastructure
