version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  create-infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Create CloudFormation Stack
          command: |
            aws cloudformation create-stack \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --template-body ec2.yml \
              --parameters param.json \
              --region $AWS_DEFAULT_REGION
workflows:
  aws-cli:
    jobs:
      - create-infrastructure
